### ISSUE TITLE
Meeting proposal: Do `Vec` and `Box` have an aliasing requirement?

### ISSUE THREAD

**Issue by chorman0773** [rust-lang/opsem-team#14]
# Summary

This meeting will discuss the aliasing requirements on `Vec` and `Box` to see if consensus exists at least as to the question of whether such aliasing requierments exist. If consensus exists that some exist, the meeting may cover what the requirements are to an extent, but the primary focus in on the yes or no question. 

## Reading

UCG Issue: https://github.com/rust-lang/unsafe-code-guidelines/issues/326

Prior Zulip Topic: https://rust-lang.zulipchat.com/#narrow/stream/136281-t-opsem/topic/Making.20Box.20allow.20aliasing

A meeting document will be written up prior to the meeting. 

# Comment policy

These issues are meant to be used as an "announcements channel" regarding the proposal, and not as a
place to discuss the technical details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision. In the meantime, if you have
questions or ideas, ping the proposers on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/content/about/chat-platform.md

**Comment by RalfJung** [comment]
@chorman0773 what shal we do with this issue? Could you post a short summary of the discussion?

I don't think we had any concrete post-meeting actions, we kind of came out of it without much of a conclusion.

**Comment by chorman0773** [comment]
Summary as recorded

> `Box` and `Vec` are imbued with langauge magic, and their aliasing concerns are major concerns in the ecosystem, with a wide variety of common pain points that the ecosystem runs into (ala `StableDeref` and similar). With `Box`, the situation is simple than `Vec`, as this would be a weakening of guarantees, whereas it would be an addition for `Vec`.


> Answer to question posed: No, we cannot currently answer the question.

> Possible solutions to advance on the question:
* Attributes to opt-out or opt-in to various behaviours, allowing stdlib types to either have or not have aliasing constraints without intruding on unsafe code that wants or does not want the constraints.
* `MaybeDangling<Box<T>>` could have place-deref behaviour like `Box<T>`


I'm not sure there's a lot to do from here, except either wait for `MaybeDangling` or the attribute design, so this issue can probably be closed.
