### ISSUE TITLE
Meeting Proposal: Documentation and resources for unsafe code

### ISSUE THREAD

**Issue by JakobDegen** [rust-lang/opsem-team#4]
# Summary

There are currently a number of resources for learning how to write unsafe code. Within rust-lang, there's at least the rustonomicon, the UCG repo (both issues and checked in stuff), and various tidbits lying around in the standard library docs and the reference. There are lots of external projects too, with varying degrees of relation to the project.

We should figure out what the story for these resources ought to look like. What is out of date and needs to be removed? What should the team take ownership of? What are the resources that we want people to be going to?

A meeting on this topic would require a non-trivial amount of pre-work; someone would need to aggregate all the existing resources, and come up with at least some options for answers to the above questions. I also expect that there are stakeholders outside of the team who would probably be interested (@Manishearth maybe?) and are worth coordinating with.

## Reading

Hopefully will be prepared for the meeting.

# Comment policy

These issues are meant to be used as an "announcements channel" regarding the proposal, and not as a
place to discuss the technical details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision. In the meantime, if you have
questions or ideas, ping the proposers on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/content/about/chat-platform.md

**Comment by Lokathor** [comment]
Zulip Thread created: https://rust-lang.zulipchat.com/#narrow/stream/136281-t-opsem/topic/Meeting.20Proposal.3A.20Documentation.20and.20resources.20for.20unsaf.2E.2E.2E.234

**Comment by RalfJung** [comment]
What's the status of this? A meeting has been had, right (on 2023-07-11)? What's the conclusion? Can the issue be closed?

**Comment by RalfJung** [comment]
I will close the issue since it doesn't seem like there are any post-meeting actions to track here. Please reopen if you have anything to track. :)
