### ISSUE TITLE
Meeting Proposal: Valid uses of addr_of! (and requirements of places)

### ISSUE THREAD

**Issue by saethlin** [rust-lang/opsem-team#9]
# Summary

The implementation of `addr_of!` is just:
```
pub macro addr_of($place:expr) {
    &raw const $place
}
```

Then the documentation for `ptr::addr_of!` says:

> Creating a reference with &/&mut is only allowed if the pointer is properly aligned and points to initialized data.
> ...
> This macro can create a raw pointer _without_ creating a reference first.
> 
> Note, however, that the `expr` in `addr_of!(expr)` is still subject to all the usual rules.

The first paragraph of the documentation suggests that `addr_of!` is useful for creating misaligned pointers. Then the second paragraph warns about "all the usual rules", which are not defined anywhere. So reading this documentation, one can come away with either impression about whether this program is well-defined or not:
```rust
struct Misalignment {
    a: u32,
}

fn main() {
    let items: [Misalignment; 2] = [Misalignment { a: 0 }, Misalignment { a: 1 }]; 
    unsafe {
        let ptr: *const Misalignment = items.as_ptr().cast::<u8>().add(1).cast::<Misalignment>();
        let _ptr = core::ptr::addr_of!((*ptr).a);
    }   
}
```
Do "the usual rules" forbid the misaligned dereference inside of `addr_of!`? Or is `addr_of!` exempted because _that's the whole reason it exists_?

The goal of this meeting is to decide if we are able to bless this use of `addr_of!`, whether we probably need it to be UB, or if we wish to delay this decision. If we wish to delay this decision, then we also have the goal of deciding what guidance we should offer to our users in the meantime.

## Reading

- https://github.com/rust-lang/rust/pull/112026
- https://github.com/rust-lang/unsafe-code-guidelines/issues/319

HackMD: https://hackmd.io/YjSceBPISBiGwsiqt9cDdw

# Comment policy

These issues are meant to be used as an "announcements channel" regarding the proposal, and not as a
place to discuss the technical details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision. In the meantime, if you have
questions or ideas, ping the proposers on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/content/about/chat-platform.md

**Comment by RalfJung** [comment]
I think this should be slightly broader -- basically this is about when exactly which properties of a place are required to avoid UB. Currently we have "whenever a place is constructed, it must be aligned and dereferenceable". That's also what Miri implements. In MiniRust we have "arbitrary places can be constructed; when doing a place projection, it must be inbounds (same rules as `ptr::offset`); when loading from a place, it must be aligned and dereferenceable". Other options are conceivable.

I'm happy to help draft the discussion document.

**Comment by saethlin** [comment]
Yeah we should definitely work together. I'll start something then we can iterate on it together.

But mostly here I'm just saving a link to this very interesting footnote for myself: https://github.com/rust-lang/rust/issues/112504#issue-1751118076

**Comment by RalfJung** [comment]
I realized we don't even have a UCG issue for the "place validity invariant", so here is one: https://github.com/rust-lang/unsafe-code-guidelines/issues/418. That's basically what we want to resolve in this meeting, I think.

**Comment by saethlin** [comment]
I've started a writeup here, but it's only about my questions about `addr_of!` so far. I think others should amend it with their questions about place validity: https://hackmd.io/@r7Ge5hUhSrqXom8A7Ga3XQ/HknsMDID2

**Comment by RalfJung** [comment]
Summary:
nobody in the room was opposed to change the rules of `*` expression evaluation such that, when operating on a raw pointer, nothing at all happens -- we just turn the pointer value into a place, with no chance of UB.

There was some concern that `addr_of!((*ptr).field)` can still be UB due to doing out-of-bounds pointer arithmetic (so `addr_of!` might still have more UB than expected), but:
- this is considered rarer and less surprising than violating alignment, so overall the proposed change still helps
- we almost definitely want to remove the "dereferenceable" check from raw-pointer `*` (for cases like `dirent`); keeping the "aligned" check at that point seems entirely ad-hoc and unnecessary

**Comment by saethlin** [comment]
I think there are more tasks than that? Keeping this list more for myself than anything:

- [ ] Update The Reference with t-opsem FCP
- [ ] Update the docs of `addr_of!` after The Reference
- [ ] Update Miri?
- [ ] Update `CheckAlignment` @saethlin

**Comment by chorman0773** [comment]
I can take doing the `addr_of!` docs PR.

**Comment by RalfJung** [comment]
Right there's a bunch of follow-ups to do. I can take care of Miri.

FWIW I updated MiniRust to do the dereferenceable+aligned check on references but not raw pointers.

**Comment by RalfJung** [comment]
The reference and Miri are updated. :)

From the todo list above, we still have
- to update the `addr_of!` docs, @chorman0773 do you still plan to do that
- to update the `CheckAlignment` pass, @saethlin I guess that's https://github.com/rust-lang/rust/pull/113343 ?

**Comment by saethlin** [comment]
Yeah, I'll reshape that PR to match what is checked elsewhere.

**Comment by RalfJung** [comment]
All the action items  tracked above have PRs on their way. So I don't think we need to still keep this issue here open.

Glad to have this long-standing open issue finally fully resolved. :)
